name: hello_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  provider: ^6.0.0
  intl: ^0.17.0
  flutter:
    sdk: flutter
  sqflite: ^2.2.5
  path:
  flutter_launcher_icons: "^0.13.0"
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: assets/note.png